# Generated by Django 3.0.5 on 2024-05-31 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Phong',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('customer', models.IntegerField()),
                ('doctor', models.IntegerField()),
                ('timeStart', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(choices=[('Cho kham', 'Cho kham'), ('Dang kham', 'Dang kham'), ('Kham xong', 'Kham xong')], default='Cho Kham', max_length=20)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Phong')),
            ],
        ),
    ]
