# Generated by Django 3.0.5 on 2024-05-31 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhyt', models.BooleanField(default=False)),
                ('dungtuyen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mach', models.CharField(max_length=100)),
                ('nhipTho', models.CharField(max_length=100)),
                ('chieuCao', models.CharField(max_length=100)),
                ('canNang', models.CharField(max_length=100)),
                ('thanNhiet', models.CharField(max_length=100)),
                ('bmi', models.CharField(max_length=100)),
                ('tieuSuBenhLi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'input_information',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('customer', models.IntegerField()),
                ('doctor', models.IntegerField()),
                ('chanDoanLamSang', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ketQua', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Ngoai tru', 'Ngoai tru'), ('Noi tru', 'Noi tru')], default='Ngoai tru', max_length=20)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('bed', models.IntegerField(blank=True, null=True)),
                ('type_room', models.IntegerField(blank=True, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.InputInformation')),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
    ]
