# Generated by Django 3.0.5 on 2024-05-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField()),
            ],
            options={
                'verbose_name': 'patient_supply',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'producer',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sl', models.IntegerField()),
                ('price_day', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Producer')),
            ],
            options={
                'verbose_name': 'supply',
            },
        ),
        migrations.CreateModel(
            name='ItemPatientSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStartThue', models.DateTimeField(auto_now=True)),
                ('sl', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('patient_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.PatientSupply')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.Supply')),
            ],
            options={
                'verbose_name': 'item_patient_supply',
            },
        ),
    ]
